# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

bella_goth = User.create(first_name: "Bella",
                         last_name: "Goth",
                         email: "bellagoth@markdown.com",
                         password: "12345678",
                         biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare quam felis, vel sollicitudin risus congue egestas. In congue venenatis dui, sed viverra ipsum pulvinar at. Praesent eleifend lorem erat, id fringilla est consectetur vitae. Suspendisse feugiat facilisis lorem, vel fringilla erat molestie at. Vivamus pretium tortor a justo varius, eu posuere mi volutpat. Praesent lacinia viverra ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris sit amet aliquam purus, ornare maximus enim.")
betty_newbie = User.create(first_name: "Betty",
                           last_name: "Newbie",
                           email: "bettynewbie@markdown.com",
                           password: "12345678",
                           biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare quam felis, vel sollicitudin risus congue egestas. In congue venenatis dui, sed viverra ipsum pulvinar at. Praesent eleifend lorem erat, id fringilla est consectetur vitae. Suspendisse feugiat facilisis lorem, vel fringilla erat molestie at. Vivamus pretium tortor a justo varius, eu posuere mi volutpat. Praesent lacinia viverra ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris sit amet aliquam purus, ornare maximus enim.")

post_one = Post.new(title: "TWICE’s ‘Formula’ Equals Success on Top Album Sales Chart", content: "**TWICE** collects its second top 10 album on *Billboard*’s [Top Album Sales](https://www.billboard.com/charts/top-album-sales) chart, and largest sales week yet, as *Formula of Love: O+T=<3* debuts at No. 2 on the Nov. 27-dated chart. It sold 58,000 copies in the U.S. in the week ending Nov. 18, marking the biggest sales frame for the South Korean girl group yet, surpassing the 43,000-sales launch of *Taste of Love* in June (No. 1 debut).\r\n\r\n*Formula of Love: O+T=<3*’s 58,000 sold, physical album sales comprise 56,000 (all from its CD editions) and digital album sales comprise 2,000. Like many K-pop releases, the CD edition of the new album was issued in multiple collectible packages (six, including two Target-exclusive editions) each with a set of standard internal paper goods (photobook, sticker, photocard set, poster, etc.) and randomized elements. (As an example of the latter, each CD package contains four of 60 different photo cards – effectively trading cards branded to an individual member of the *nine-person act*).\r\n\r\nThe South Korean girl group hit the top 10 earlier in 2021 with the No. 1 debut *Taste of Love: The 10th Mini Album* (June 26 chart).\r\nThe new album was preceded by the track “The Feels,” which became the group’s first charting effort on the [Billboard Hot 100](https://www.billboard.com/charts/hot-100/) songs chart, spending a week at No. 83 on the Oct. 16-dated list.", user: bella_goth)
post_one_thumbnail = URI.open("https://i.imgur.com/xiBuGKr.jpg")
post_one.thumbnail.attach(io: post_one_thumbnail, filename: "xiBuGKr.jpg")
post_one.save

post_two = Post.new(title: "5 Reasons Why Ariana Grande Became The Queen of the Hot 100 No. 1 Debut", content: "On last week’s Billboard Hot 100 chart, **Ariana Grande** extended a record that she already set herself earlier this year when *“Positions”*, the lead single from her sixth album of the same name, launched at No. 1 on the tally (the song **slips to No. 2** on this week’s chart, as Grande’s Positions album **starts at No. 1** on the Billboard 200).\r\n\r\nWith *“Positions”* crashing in atop the **Hot 100**, Grande now has five total No. 1 debuts on the chart: *“Thank U, Next,” “7 Rings,” “Stuck With U”* with Justin Bieber, *“Rain On Me”* with Lady Gaga, and *“Positions.”*\r\n\r\nAll five hits were released in the past two years — after Grande couldn’t quite snag a No. 1 single for the first five years of her career. Now, there might not be a more bankable pop star than Grande when it comes to launching a new track atop the Hot 100, and the record she set earlier this year with “Rain On Me” has only grown.\r\n\r\n1. She’s always been a top 10 mainstay.\r\n2. She released Thank U, Next, which pushed her to a new level.\r\n3. She released smart collaborations during her downtime.\r\n4. She engineered a surprising, well-executed return\r\n5. She’s continued to evolve, while keeping her singles quality high.\r\n\r\nThat daring has proven critically effective, too: Thank U, Next became Grande’s first project to receive an album of the year nod at the Grammys last year, while “7 Rings” was her breakthrough in the record of the year category. Based on the strong showing of “Rain On Me” at this year’s MTV Video Music Awards, where it won song of the year, Grande’s collaboration with Gaga could have a big night at the 2021 Grammys, as could “Stuck With U” alongside Bieber (Positions, and its title track, have to be penciled in as contenders for the 2022 Grammys ceremony, having missed the 2021 eligibility period).\r\n\r\nAs Grande has vaulted into the upper echelon of pop superstars, her No. 1 debuts on the Hot 100 encapsulate how her critical and commercial appeal keeps soaring higher. Everybody loves what she’s doing right now, and as her apex continues, so may her record of Hot 100-topping debuts.", user: betty_newbie)
post_two_thumbnail = URI.open("https://i.imgur.com/tTJZNgQ.jpg")
post_two.thumbnail.attach(io: post_two_thumbnail, filename: "tTJZNgQ.jpg")
post_two.save

post_three = Post.new(title: "ITZY releases 'Crazy In Love' and show us their lovely side on their latest album", content: "**ITZY’s** Crazy in Love: The 1st Album debuts at No. 1 on Billboard’s Top Album Sales chart (dated Oct. 9), marking the first leader, and second entry, for the Korean pop group. The set, which is promoted as the act’s debut full-length studio album, sold 22,000 copies in the U.S. in the week ending Sep. 30, according to MRC Data.\r\n\r\nCrazy follows one other entry for the group, the Guess Who EP, which peaked at No. 23 this May.\r\n\r\nCrazy in Love: The 1st Album leads five debuts in the top 10 on Top Album Sales, as new efforts from Angels & Airwaves, YoungBoy Never Broke Again, Billy Strings and Sufjan Stevens and Angelo De Augustine arrive.\r\n\r\nBillboard’s Top Album Sales chart ranks the top-selling albums of the week based only on traditional album sales. The chart’s history dates back to May 25, 1991, the first week Billboard began tabulating charts with electronically monitored piece count information from SoundScan, now MRC Data. Pure album sales were the measurement solely utilized by the Billboard 200 albums chart through the list dated Dec. 6, 2014, after which that chart switched to a methodology that blends album sales with track equivalent album units and streaming equivalent album units. For all chart news, follow @billboard and @billboardcharts on both Twitter and Instagram.\r\nOf Crazy in Love: The 1st Album’s sales of 22,000, physical album sales comprise 21,000 (all from CD sales) and 1,000 via digital download. Like many K-pop releases, the CD edition of the album was issued in multiple collectible packages (including a Target-exclusive edition).\r\n\r\nITZY replaces another Korean pop act at No. 1, as NCT 127’s Sticker: The 3rd Album falls from No. 1 to No. 2 in its second week (15,000; down 76%).\r\n\r\nAngels & Airwaves’ new studio album Lifeforms bows at No. 3 with 13,000 sold while YoungBoy Never Broke Again’s Sincerely, Kentrell starts at No. 4 with 10,000. Metallica’s self-titled former No. 1 is up one spot to No. 5 with 9,000 (down 26%) and Olivia Rodrigo’s chart-topping Sour climbs 7-6 with nearly 9,000 (down 26%).\r\n\r\nBilly Strings’ Renewal launches at No. 7 (8,000 sold), Billie Eilish’s former No. 1 Happier Than Ever climbs 11-8 (7,000; down 9%), Sufjan Stevens and Angelo De Augustine’s A Beginner’s Mind debuts at No. 9 (nearly 7,000) and Kacey Musgraves’ Star-Crossed falls 4-10 in its third week (nearly 7,000; down 54%).", user: bella_goth)
post_three_thumbnail = URI.open("https://i.imgur.com/7feWJW5.jpg")
post_three.thumbnail.attach(io: post_three_thumbnail, filename: "7feWJW5.jpg")
post_three.save
